/*
 * PROJECT:    Mobility
 * FILE:       Mobility.Memory.SmallHeap.h
 * PURPOSE:    Definition for Mobility Small Memory Heap
 *
 * LICENSE:    The MIT License
 *
 * MAINTAINER: MouriNaruto (Kenji.Mouri@outlook.com)
 */

#ifndef MOBILITY_MEMORY_SMALLHEAP
#define MOBILITY_MEMORY_SMALLHEAP

#define MILE_MOBILITY_ENABLE_MINIMUM_SAL
#include <Mile.Mobility.Portable.Types.h>

/*
 * Small Heap v1
 * - Signature: 'S', 'H', 'v', '1'
 *   - Constant char value: '1vHS'
 *   - Little Endian UInt32 Value: 0x31764853
 * - Size: Fixed 64 KiB
 * - Unit Size: 8 Bytes
 *   - Because start address of the user area is aligned with 8 bytes.
 */

#define MO_MEMORY_SMALL_HEAP_SIGNATURE 0x31764853
#define MO_MEMORY_SMALL_HEAP_SIZE (64 * 1024)
#define MO_MEMORY_SMALL_HEAP_HEADER_SIZE 8
#define MO_MEMORY_SMALL_HEAP_HEADER_UNITS \
    (MO_MEMORY_SMALL_HEAP_HEADER_SIZE >> 3)
#define MO_MEMORY_SMALL_HEAP_PHYSICAL_UNITS \
    (MO_MEMORY_SMALL_HEAP_SIZE >> 3)
#define MO_MEMORY_SMALL_HEAP_BITMAP_SIZE \
    (MO_MEMORY_SMALL_HEAP_PHYSICAL_UNITS >> 3)
#define MO_MEMORY_SMALL_HEAP_BITMAP_UNITS \
    (MO_MEMORY_SMALL_HEAP_BITMAP_SIZE >> 3)
#define MO_MEMORY_SMALL_HEAP_USER_AREA_SIZE ( \
    MO_MEMORY_SMALL_HEAP_SIZE - \
    MO_MEMORY_SMALL_HEAP_HEADER_SIZE - \
    MO_MEMORY_SMALL_HEAP_BITMAP_SIZE)
#define MO_MEMORY_SMALL_HEAP_INITIAL_ALLOCATED_UNITS ( \
    MO_MEMORY_SMALL_HEAP_HEADER_UNITS + \
    MO_MEMORY_SMALL_HEAP_BITMAP_UNITS)
#define MO_MEMORY_SMALL_HEAP_INITIAL_HINT_UNIT ( \
    MO_MEMORY_SMALL_HEAP_INITIAL_ALLOCATED_UNITS)

typedef struct _MO_MEMORY_SMALL_HEAP_HEADER
{
    MO_UINT32 Signature;
    MO_UINT16 AllocatedUnits;
    MO_UINT16 HintUnit;
} MO_MEMORY_SMALL_HEAP_HEADER, *PMO_MEMORY_SMALL_HEAP_HEADER;
MO_C_STATIC_ASSERT(sizeof(MO_MEMORY_SMALL_HEAP_HEADER) \
    == MO_MEMORY_SMALL_HEAP_HEADER_SIZE);

typedef struct _MO_MEMORY_SMALL_HEAP
{
    MO_MEMORY_SMALL_HEAP_HEADER Header;
    MO_UINT8 BitMap[MO_MEMORY_SMALL_HEAP_BITMAP_SIZE];
    MO_UINT8 UserArea[MO_MEMORY_SMALL_HEAP_USER_AREA_SIZE];
} MO_MEMORY_SMALL_HEAP, *PMO_MEMORY_SMALL_HEAP;
MO_C_STATIC_ASSERT(sizeof(MO_MEMORY_SMALL_HEAP) == MO_MEMORY_SMALL_HEAP_SIZE);

#define MO_MEMORY_SMALL_HEAP_ITEM_HEADER_SIZE 8

typedef struct _MO_MEMORY_SMALL_HEAP_ITEM_HEADER
{
    MO_UINT16 HeapHeaderOffsetUnits;
    MO_UINT16 AllocatedUnits;
    MO_UINT16 RequestedSize;
    MO_UINT16 Checksum;
} MO_MEMORY_SMALL_HEAP_ITEM_HEADER, *PMO_MEMORY_SMALL_HEAP_ITEM_HEADER;
MO_C_STATIC_ASSERT(sizeof(MO_MEMORY_SMALL_HEAP_ITEM_HEADER) \
    == MO_MEMORY_SMALL_HEAP_ITEM_HEADER_SIZE);

#endif // !MOBILITY_MEMORY_SMALLHEAP
