/*
 * PROJECT:    Mobility
 * FILE:       float.h
 * PURPOSE:    Definition for the C Standard Library <float.h> header
 *
 * LICENSE:    The MIT License
 *
 * MAINTAINER: MouriNaruto (Kenji.Mouri@outlook.com)
 */

#ifndef MOBILITY_RUNTIME_FLOAT
#define MOBILITY_RUNTIME_FLOAT

#include <Mile.Mobility.Portable.Types.h>

#define __STDC_VERSION_FLOAT_H__ 202311L

#define FLT_ROUNDS MO_FP_ROUNDS
#define FLT_EVAL_METHOD MO_FP_EVAL_METHOD
#define FLT_HAS_SUBNORM MO_FP32_HAS_SUBNORM
#define DBL_HAS_SUBNORM MO_FP64_HAS_SUBNORM
#define LDBL_HAS_SUBNORM MO_FP64_HAS_SUBNORM
#define FLT_RADIX MO_FP_RADIX
#define FLT_MANT_DIG MO_FP32_MANT_DIG
#define DBL_MANT_DIG MO_FP64_MANT_DIG
#define LDBL_MANT_DIG MO_FP64_MANT_DIG
#define FLT_DECIMAL_DIG MO_FP32_DECIMAL_DIG
#define DBL_DECIMAL_DIG MO_FP64_DECIMAL_DIG
#define LDBL_DECIMAL_DIG MO_FP64_DECIMAL_DIG
#define DECIMAL_DIG MO_FP64_DECIMAL_DIG
#define FLT_DIG MO_FP32_DIG
#define DBL_DIG MO_FP64_DIG
#define LDBL_DIG MO_FP64_DIG
#define FLT_MIN_EXP MO_FP32_MIN_EXP
#define DBL_MIN_EXP MO_FP64_MIN_EXP
#define LDBL_MIN_EXP MO_FP64_MIN_EXP
#define FLT_MIN_10_EXP MO_FP32_MIN_10_EXP
#define DBL_MIN_10_EXP MO_FP64_MIN_10_EXP
#define LDBL_MIN_10_EXP MO_FP64_MIN_10_EXP
#define FLT_MAX_EXP MO_FP32_MAX_EXP
#define DBL_MAX_EXP MO_FP64_MAX_EXP
#define LDBL_MAX_EXP MO_FP64_MAX_EXP
#define FLT_MAX_10_EXP MO_FP32_MAX_10_EXP
#define DBL_MAX_10_EXP MO_FP64_MAX_10_EXP
#define LDBL_MAX_10_EXP MO_FP64_MAX_10_EXP
#define FLT_MAX MO_FP32_MAX
#define DBL_MAX MO_FP64_MAX
#define LDBL_MAX MO_FP64_MAX
#define FLT_EPSILON MO_FP32_EPSILON
#define DBL_EPSILON MO_FP64_EPSILON
#define LDBL_EPSILON MO_FP64_EPSILON
#define FLT_MIN MO_FP32_MIN
#define DBL_MIN MO_FP64_MIN
#define LDBL_MIN MO_FP64_MIN
#define FLT_TRUE_MIN MO_FP32_TRUE_MIN
#define DBL_TRUE_MIN MO_FP64_TRUE_MIN
#define LDBL_TRUE_MIN MO_FP64_TRUE_MIN
#define INFINITY MO_FP_INFINITY
#define NAN MO_FP_NAN
#define FLT_SNAN MO_FP32_SNAN
#define DBL_SNAN MO_FP64_SNAN
#define LDBL_SNAN MO_FP64_SNAN

#endif // !MOBILITY_RUNTIME_FLOAT
