/*
 * PROJECT:    Mobility
 * FILE:       limits.h
 * PURPOSE:    Definition for the C Standard Library <limits.h> header
 *
 * LICENSE:    The MIT License
 *
 * MAINTAINER: MouriNaruto (Kenji.Mouri@outlook.com)
 */

#ifndef MOBILITY_RUNTIME_LIMITS
#define MOBILITY_RUNTIME_LIMITS

#include <Mile.Mobility.Portable.Types.h>

#define __STDC_VERSION_LIMITS_H__ 202311L

#define BITINT_MAXWIDTH MO_UINT64_WIDTH
#define BOOL_MAX MO_TRUE
#define BOOL_WIDTH 1
#define CHAR_BIT MO_UINT8_WIDTH
#define CHAR_MAX MO_CHAR_MAX
#define CHAR_MIN MO_CHAR_MIN
#define CHAR_WIDTH MO_CHAR_WIDTH
#define INT_MAX MO_INT32_MAX
#define INT_MIN MO_INT32_MIN
#define INT_WIDTH MO_INT32_WIDTH
#define LLONG_MAX MO_INT64_MAX
#define LLONG_MIN MO_INT64_MIN
#define LLONG_WIDTH MO_INT64_WIDTH
#define LONG_MAX MO_INT32_MAX
#define LONG_MIN MO_INT32_MIN
#define LONG_WIDTH MO_INT32_WIDTH
#define MB_LEN_MAX 6
#define SCHAR_MAX MO_INT8_MAX
#define SCHAR_MIN MO_INT8_MIN
#define SCHAR_WIDTH MO_INT8_WIDTH
#define SHRT_MAX MO_INT16_MAX
#define SHRT_MIN MO_INT16_MIN
#define SHRT_WIDTH MO_INT16_WIDTH
#define UCHAR_MAX MO_UINT8_MAX
#define UCHAR_WIDTH MO_UINT8_WIDTH
#define UINT_MAX MO_UINT32_MAX
#define UINT_WIDTH MO_UINT32_WIDTH
#define ULLONG_MAX MO_UINT64_MAX
#define ULLONG_WIDTH MO_UINT64_WIDTH
#define ULONG_MAX MO_UINT32_MAX
#define ULONG_WIDTH MO_UINT32_WIDTH
#define USHRT_MAX MO_UINT16_MAX
#define USHRT_WIDTH MO_UINT16_WIDTH

#endif // !MOBILITY_RUNTIME_LIMITS
