<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
    <GenerateRuntimeConfigurationFiles Condition="'$(TargetFramework)' == 'netstandard2.0'">true</GenerateRuntimeConfigurationFiles>
    <LangVersion>default</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="10.0.11" />
    <PackageReference Include="System.Text.Json" Version="10.0.11" />
  </ItemGroup>

</Project>
